### PR TITLE
User logs for all read queries

### PR DESCRIPTION
**Pull request by timclifford**
Re: https://github.com/uselagoon/lagoon/issues/3519

### CODE REVIEW

**Comment by Schnitzel** [comment]
@timclifford thanks very much for this, this is super great, couple of questions:

1. in my understanding this logs each individual query of a full graphql query, which is great. But would it also be possible to log the original graphql query itself?
2. Is there any possibility to get some timing data for each of these individual queries? This might be too complex and happy to ditch this for the first version, but was wondering if this is maybe easy to add

**Comment by Schnitzel** [comment]
Discussed with Lagoon team
- we would want a new `meta.level` field for these read queries: `user_query` to be able to easily filter for them in the logs.
- newrelic provides us timing information already
- @bomoko will work on logging the whole query

**Comment by shreddedbacon** [comment]
It might be an idea to wrap these in a feature, so it can be enabled/disabled as required?

**Comment by tobybellwood** [comment]
To be addressed in a Lagoon API audit logging overhaul

**Pull request closed without merging**
